spring:
  application:
    name: ${artifactName}
  profiles:
    active:
      - ${activeProfile}

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

feign.hystrix.enabled: true